# Numpy

In [1]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [2]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [3]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32
8


In [6]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[6.  7.5]
 [8.  1. ]]


In [11]:
data6 = np.arange(15,1,-1)
print(data6)

[15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [ ]:
data7 = np.eye(5)
print(data7)

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1.0, 2.0, 3.0], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [17]:
arr1 + arr2

array([2., 4., 6.])

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [18]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [20]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Tirando raiz quadrada do Array: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Tirando raiz quadrada do Array: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [22]:
arr = [2,14,3,6,8,3,10,222,4]
arr = np.array(arr)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12 #broadcast
print(arr)

[  2  14   3   6   8   3  10 222   4]
3
[  3  10 222]
[ 2 14  3  6  8 12 12 12  4]


In [23]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    2    14     3     6     8    12 12345    12     4]


In [24]:
arr2 = arr[5:8].copy()
arr2[0] = 98
print(arr2)
print(arr)

[   98 12345    12]
[    2    14     3     6     8    12 12345    12     4]


In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0,2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [27]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


## TODO

### 1)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [1]:
# Resposta

import numpy as np

def sub_array(array, x, y):
    return array[(array >= x) & (array <= y)].copy()

lista = [10,3,7,5,8,23,15]
arr = np.array(lista)
arr_resp = sub_array(arr,6,20)

print ('original: ',arr)
print ('alterado:', arr_resp)


original:  [10  3  7  5  8 23 15]
alterado: [10  7  8 15]


## 2)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [1 2 3; 4 5 6; 7 8 9]

resultado = [2 3 3; 5 6 6; 8 9 9]


Essa função pode ajudar: np.empty_like() 

In [5]:
# Resposta
import numpy as np

vetor = np.array([1,1,0])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

soma = matriz + vetor
print('matriz original:\n', matriz)                             
print('vetor a somar: ', vetor)
print('\n')
print('matriz resultante:\n', soma)

matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
vetor a somar:  [1 1 0]


matriz resultante:
 [[2 3 3]
 [5 6 6]
 [8 9 9]]


## Transposição

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

## Flattening

In [ ]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

## Funções Universais

In [ ]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
np.exp(arr) #e^x

## Localização baseada em Condição e Métodos Estatísticos

In [ ]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
import timeit

In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

In [ ]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

## Álgebra Linear

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

In [ ]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print(mat)
print(inv(mat)) #inversa

## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [ ]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

In [ ]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(42) # reset seed
print(np.random.random())

In [ ]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

## Vectorize

In [ ]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

In [ ]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

## Aplicar uma função – coluna ou linha

In [ ]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

In [ ]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

## Outros Métodos

In [ ]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

In [ ]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## TODO Section

### 3)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [ ]:
# resposta

### 4)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

In [ ]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [ ]:
# Resposta