# Numpy

In [2]:
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [2]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [3]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)
print()
print(arr2.dtype)
print()
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]

2

(2, 4)

int32

8


In [6]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print()
print(data4)
print()
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[6.  7.5]
 [8.  1. ]]


In [7]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [11]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [13]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Tirando Raiz quadrada de cada elemento: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Tirando Raiz quadrada de cada elemento: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [15]:
arr = [2,14,3,6,8,3,10,222,4]
arr = np.array(arr)
print(arr)
print()
print(arr[5])
print()
print(arr[5:8])
print()
arr[5:8] = 12
print(arr)

[  2  14   3   6   8   3  10 222   4]

3

[  3  10 222]

[ 2 14  3  6  8 12 12 12  4]


In [16]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    2    14     3     6     8    12 12345    12     4]


In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[2][2], arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
9 3


In [5]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


## TODO

### 1)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [22]:
# Resposta
import numpy as np
def interval(vetor,x = 6,y = 20):
    return np.sort(vetor[(vetor > x) & (vetor < y)])

vetor = np.array([10,3,7,5,8,23,15])
interval(vetor)

array([ 7,  8, 10, 15])

In [21]:
x = np.array([1,2,3,4,5])
x[x>=3]

array([3, 4, 5])

## 2)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [[1 2 3]; [4 5 6]; [7 8 9]]

resultado = [[2 3 3; 5 6 6; 8 9 9]]


Essa função pode ajudar: np.empty_like() 

In [26]:
# Resposta
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 1, 0])
result = np.empty_like(m)
print(result)
print()
for i in range(m.shape[0]):
    result[i, :] = m[i, :] + v
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3 3]
 [5 6 6]
 [8 9 9]]


In [24]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape[0]

3

## Transposição

In [3]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [6]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [7]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
print()
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]



array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [8]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [9]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [10]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [11]:
arr = np.random.randn(4, 4)
print(arr)
print()
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print()
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[-1.22763435 -1.68571356 -0.29261019 -0.81375304]
 [ 0.53013072  0.98434022 -0.58695256  0.93893805]
 [-2.18297229 -0.02266458 -0.28369785 -1.5273352 ]
 [-0.46768127  0.79674647 -0.16221631  1.37512061]]

[[-2 -2 -2 -2]
 [ 2  2 -2  2]
 [-2 -2 -2 -2]
 [-2  2 -2  2]]

[[-1.22763435 -1.68571356 -0.29261019 -0.81375304]
 [ 2.          2.         -0.58695256  2.        ]
 [-2.18297229 -0.02266458 -0.28369785 -1.5273352 ]
 [-0.46768127  2.         -0.16221631  2.        ]]


In [12]:
arr = np.random.randn(5, 4)
print(arr)
print()
print(arr.mean()) #ou np.mean(arr)
print()
print(arr.sum())
print()
print(arr.mean(axis=1)) #linhas
print()
print(arr.mean(axis=0)) # colunas

[[ 0.30460361  0.50735244 -0.58114687  0.60488483]
 [-0.60788516  1.19515969  1.96686808 -2.60122919]
 [-0.28480734 -1.4055511   0.41822913  0.09698204]
 [ 2.27300064 -1.30700461  0.36271478  0.22442997]
 [ 1.53052672 -0.62962161 -0.64357434  0.24919698]]

0.08365643457763812

1.6731286915527623

[ 0.2089235  -0.01177164 -0.29378682  0.38828519  0.12663194]

[ 0.6430877  -0.32793304  0.30461816 -0.28514708]


 ## Álgebra Linear

In [13]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
print()
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


In [14]:
print(x.shape)
print(y.shape)
print(z.shape)

(2, 3)
(3, 2)
(2, 2)


In [15]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print()
print(mat)
print()
print(inv(mat)) #inversa

[[-0.17309264  0.68826919 -1.38018069 -1.49041436  1.42585334]
 [ 0.76316517 -1.53087472  0.56177257 -0.95057056 -0.42347752]
 [ 0.17888581 -0.23565053 -0.60145719 -1.06161609 -1.11155424]
 [-1.53680659 -1.30630951 -2.32281724  0.28368405 -1.05989074]
 [ 0.13056916 -0.96308682 -0.48284182 -1.23797801  0.2451021 ]]

[[ 3.02320509  0.55219649  4.06670882 -1.25497992  0.89202055]
 [ 0.55219649  5.50680381  1.83113127  1.50126968  3.04009104]
 [ 4.06670882  1.83113127  8.21085405  2.10035462  0.80630592]
 [-1.25497992  1.50126968  2.10035462  5.86501427 -1.14662828]
 [ 0.89202055  3.04009104  0.80630592 -1.14662828  4.63138721]]

[[114.83001338  -6.98966932 -69.56342984  52.76675549   7.64603713]
 [ -6.98966932   0.81283431   4.2140183   -3.35997718  -0.75281859]
 [-69.56342984   4.2140183   42.28262643 -32.01593057  -4.65564476]
 [ 52.76675549  -3.35997718 -32.01593057  24.50703457   3.68371259]
 [  7.64603713  -0.75281859  -4.65564476   3.68371259   0.95995812]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [16]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.26259519, 0.26523922, 0.51558757, 0.45617678])

In [17]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(0) # reset seed
print()
print(np.random.random())

0.3745401188473625

0.5488135039273248


In [18]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

## Vectorize

In [19]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [20]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [21]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [22]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [23]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [24]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place arr = arr.sort()
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [26]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### 3)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [29]:
# resposta
import numpy as np
a = np.array([1,4,2,6,5,7,3,0])
b = np.array([3,2,0,9,8,7])

np.setdiff1d(a,b)

array([1, 4, 5, 6])

### 4)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

In [27]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [28]:
iris_2d

array([[5.1, 3.5, 1.4, nan],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, nan, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, nan, 0.2],
       [4.9, 3

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [30]:
# Resposta
print("Número de NaN na primeira coluna: ", np.isnan(iris_2d[:, 0]).sum(),"\n")

print("Número total de NaN: ", np.isnan(iris_2d).sum(),"\n")

print("Posições de NaN na primeira coluna: ", np.where(np.isnan(iris_2d[:, 0])), "\n")

print("Substituindo NaN por 0: ")
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:8]

Número de NaN na primeira coluna:  4 

Número total de NaN:  20 

Posições de NaN na primeira coluna:  (array([ 38,  58,  71, 131], dtype=int64),) 

Substituindo NaN por 0: 


array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 0. , 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2]])